# Numpy Introduction

In [2]:
# Install Numpy
%pip install numpy


In [3]:
# Import the Libraries
import numpy as np

## What is an array?
An array is a data structure in programming that stores a collection of elements, typically of the same data type, in contiguous memory locations. It allows for efficient storage and manipulation of large amounts of data. In Python, the NumPy library provides support for arrays and various operations that can be performed on them.

In [8]:
# One Dimentional Array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [9]:
# 2 Dimentional Array
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [10]:
# shape of the data
a2.shape
# The results showing 1 Row and 6 Columns

(1, 6)

In [11]:
# shape of the data
a.shape
# The results showing 1 Column, as 1 dimentional data

(6,)

In [12]:
# 3 Dimentional array, This is usually used in Image analysis
a3 = a[np.newaxis, :, np.newaxis]
print(a3)

# shape of the data
a3.shape

# the results showing data on three axis, x, y , z

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


(1, 6, 1)

## Why do we have 1D, 2D, or 3D arrays ans where we need them in Data Science?


Arrays can have different dimensions depending on the number of axes they have. 1D arrays have a single axis, 2D arrays have two axes, and 3D arrays have three axes. 

In data science, arrays are used to store and manipulate large amounts of data. For example, a 1D array can be used to store a sequence of values, such as stock prices over time. A 2D array can be used to store a table of data, such as a spreadsheet or a database table. A 3D array can be used to store volumetric data, such as medical images or climate data.

Arrays are also used in mathematical operations, such as linear algebra and statistics. Many popular data science libraries, such as NumPy and Pandas, provide support for arrays and various operations that can be performed on them.

## Basic ways to Create Arrays in Numpy
------

In [13]:
a = np.array([1,2,3,4,5,6])
b = np.array([(1,2,3,4,5,6),(4,5,6,7,8,9)])

In [17]:
print(a.shape)
print(b.shape)


(6,)
(2, 6)


In [19]:
zeros = np.zeros((3,4)) # (rows, Columns)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
ones = np.ones((2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# full Array - this is used for all other numbers except 0 and 1
twos = np.full((2,3), 2) # this is 2 value array
twos

array([[2, 2, 2],
       [2, 2, 2]])

## Matrix of Array

In [24]:
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
type(identity)

numpy.ndarray

In [25]:
identity.dtype

dtype('float64')

### Difference between `dtype` and `type`


In NumPy, `dtype` and `type` are both used to describe the data type of an array, but they have different meanings.

`dtype` refers to the data type of the elements in the array. It is a NumPy object that specifies the size and layout of the memory buffer that contains the array data. Examples of `dtype` include `int64`, `float32`, and `bool`.

`type` refers to the type of the array object itself. It is a Python built-in function that returns the type of an object. In the case of NumPy arrays, the `type` function returns `<class 'numpy.ndarray'>`.

Here's an example to illustrate the difference:



In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(a.dtype)  # prints "int64"
print(type(a))  # prints "<class 'numpy.ndarray'>"

## Array Attributes

In [27]:
a.shape # shape of array

(6,)

In [28]:
len(a) # give us the number of elements in an array

6

In [31]:
identity.size # number of elements in an array

25

In [30]:
b.ndim # give us the dminetions of array

2

## Basic Operations

In [32]:
a

array([1, 2, 3, 4, 5, 6])

In [33]:
b

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [36]:
# Subtraction
g = b - a
g

array([[0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3]])

In [37]:
# Additon
h = a+ b
h

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

In [39]:
# another addtion method
h1 = np.add(a,b)
h1

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

In [42]:
# Multiplication
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36],
       [ 4, 10, 18, 28, 40, 54]])

In [41]:
# divison
j = b / a
j

array([[1.  , 1.  , 1.  , 1.  , 1.  , 1.  ],
       [4.  , 2.5 , 2.  , 1.75, 1.6 , 1.5 ]])

In [43]:
# square of each element in a
k = a**2
k

array([ 1,  4,  9, 16, 25, 36])