# Numpy Indexing and Slicing

In [1]:
# Import Numpy
import numpy as np


In [3]:
# Creat and array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a[-1]

8

In [5]:
# creat a second array of 8 digits
b = np.array([11, 12, 13, 14, 15, 16, 17, 18])
b

array([11, 12, 13, 14, 15, 16, 17, 18])

In [6]:
b[5]

16

In [12]:
c = b.reshape(4, 2)
c

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [14]:
c[0:2]

array([[11, 12],
       [13, 14]])

In [15]:
c [c<16]

array([11, 12, 13, 14, 15])

## How to create an array from Existing Data

In [16]:
# make an array from 0 to 222 with a step of 5
d = np.arange(0, 222, 5)
d


array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [18]:
len(d)

45

In [23]:
#slice the array from 0 to 100
array1 = d[25:36] # this should be index number and with in the range of the original array,
                    #for example d has max len is 45, so slicing should be in between 0 to 45.
array1

array([125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175])

In [24]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b = np.array([11, 12, 13, 14, 15, 16, 17, 18])


In [25]:
c = np.vstack((a, b)) # vertical stack

c

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [11, 12, 13, 14, 15, 16, 17, 18]])

In [26]:
# horizontal stack
d = np.hstack((a, b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 12, 13, 14, 15, 16, 17, 18])

___ 

# Martix or Marticies

In [28]:
# Create a 2x3 matrix
e = np.array([[1, 2, 3], [4, 5, 6]])
e

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 12, 13, 14, 15, 16, 17, 18])

In [48]:
d = np.arange(0, 250, 5)
d

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245])

In [49]:
len(d)

50

In [50]:
g = d.reshape(10, 5)
g

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195],
       [200, 205, 210, 215, 220],
       [225, 230, 235, 240, 245]])

In [67]:
g = d.reshape(5, 10)
g

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175, 180, 185, 190, 195],
       [200, 205, 210, 215, 220, 225, 230, 235, 240, 245]])

In [66]:
# slice a matrix
h = g[1:4, 3:7] # 1:4 defines the rows only and 3:7 defines the columns only
h

array([[ 65,  70,  75,  80],
       [115, 120, 125, 130],
       [165, 170, 175, 180]])

In [69]:
g.min(1) # min value of each row

array([  0,  50, 100, 150, 200])

In [70]:
g.min(0) # min value of each column

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [71]:
g.sum(1) # sum of each row

array([ 225,  725, 1225, 1725, 2225])

In [72]:
g.sum() # sum of each column

6125

In [73]:
g.sum(0) # sum of each column

array([500, 525, 550, 575, 600, 625, 650, 675, 700, 725])

In [74]:
g

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175, 180, 185, 190, 195],
       [200, 205, 210, 215, 220, 225, 230, 235, 240, 245]])

In [76]:
g.mean(0) # mean of each column

array([100., 105., 110., 115., 120., 125., 130., 135., 140., 145.])

In [78]:
t = np.arange(0, 16, 2).reshape(4, 2)
t

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [79]:
# add 20 in column o and 30 in column 1
t = t + [20, 30]
t

array([[20, 32],
       [24, 36],
       [28, 40],
       [32, 44]])

In [81]:
# add 2 more numbers in the array
t = np.append(t, [[36, 48]], axis=0)
t

array([[20, 32],
       [24, 36],
       [28, 40],
       [32, 44],
       [ 1,  2],
       [36, 48]])

In [82]:
t = np.vstack((t, [[50, 58]]))
t

array([[20, 32],
       [24, 36],
       [28, 40],
       [32, 44],
       [ 1,  2],
       [36, 48],
       [50, 58]])

In [83]:
g

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175, 180, 185, 190, 195],
       [200, 205, 210, 215, 220, 225, 230, 235, 240, 245]])

In [84]:
np.flip(g)

array([[245, 240, 235, 230, 225, 220, 215, 210, 205, 200],
       [195, 190, 185, 180, 175, 170, 165, 160, 155, 150],
       [145, 140, 135, 130, 125, 120, 115, 110, 105, 100],
       [ 95,  90,  85,  80,  75,  70,  65,  60,  55,  50],
       [ 45,  40,  35,  30,  25,  20,  15,  10,   5,   0]])

In [87]:
np.flip(g, 1)

array([[ 45,  40,  35,  30,  25,  20,  15,  10,   5,   0],
       [ 95,  90,  85,  80,  75,  70,  65,  60,  55,  50],
       [145, 140, 135, 130, 125, 120, 115, 110, 105, 100],
       [195, 190, 185, 180, 175, 170, 165, 160, 155, 150],
       [245, 240, 235, 230, 225, 220, 215, 210, 205, 200]])