# Numpy Introduction

In [1]:
# Install Numpy
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
# Import the Libraries
import numpy as np

## What is an array?
An array is a data structure in programming that stores a collection of elements, typically of the same data type, in contiguous memory locations. It allows for efficient storage and manipulation of large amounts of data. In Python, the NumPy library provides support for arrays and various operations that can be performed on them.

In [8]:
# One Dimentional Array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [9]:
# 2 Dimentional Array
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [10]:
# shape of the data
a2.shape
# The results showing 1 Row and 6 Columns

(1, 6)

In [11]:
# shape of the data
a.shape
# The results showing 1 Column, as 1 dimentional data

(6,)

In [12]:
# 3 Dimentional array, This is usually used in Image analysis
a3 = a[np.newaxis, :, np.newaxis]
print(a3)

# shape of the data
a3.shape

# the results showing data on three axis, x, y , z

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


(1, 6, 1)

## Why do we have 1D, 2D, or 3D arrays ans where we need them in Data Science?


Arrays can have different dimensions depending on the number of axes they have. 1D arrays have a single axis, 2D arrays have two axes, and 3D arrays have three axes. 

In data science, arrays are used to store and manipulate large amounts of data. For example, a 1D array can be used to store a sequence of values, such as stock prices over time. A 2D array can be used to store a table of data, such as a spreadsheet or a database table. A 3D array can be used to store volumetric data, such as medical images or climate data.

Arrays are also used in mathematical operations, such as linear algebra and statistics. Many popular data science libraries, such as NumPy and Pandas, provide support for arrays and various operations that can be performed on them.

## Basic ways to Create Arrays in Numpy
------

In [13]:
a = np.array([1,2,3,4,5,6])
b = np.array([(1,2,3,4,5,6),(4,5,6,7,8,9)])

In [17]:
print(a.shape)
print(b.shape)


(6,)
(2, 6)


In [19]:
zeros = np.zeros((3,4)) # (rows, Columns)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
ones = np.ones((2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# full Array - this is used for all other numbers except 0 and 1
twos = np.full((2,3), 2) # this is 2 value array
twos

array([[2, 2, 2],
       [2, 2, 2]])

## Matrix of Array

In [24]:
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
type(identity)

numpy.ndarray

In [25]:
identity.dtype

dtype('float64')

### Difference between `dtype` and `type`


In NumPy, `dtype` and `type` are both used to describe the data type of an array, but they have different meanings.

`dtype` refers to the data type of the elements in the array. It is a NumPy object that specifies the size and layout of the memory buffer that contains the array data. Examples of `dtype` include `int64`, `float32`, and `bool`.

`type` refers to the type of the array object itself. It is a Python built-in function that returns the type of an object. In the case of NumPy arrays, the `type` function returns `<class 'numpy.ndarray'>`.

Here's an example to illustrate the difference:



In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(a.dtype)  # prints "int64"
print(type(a))  # prints "<class 'numpy.ndarray'>"

## Array Attributes

In [27]:
a.shape # shape of array

(6,)

In [28]:
len(a) # give us the number of elements in an array

6

In [31]:
identity.size # number of elements in an array

25

In [30]:
b.ndim # give us the dminetions of array

2

## Basic Operations

In [32]:
a

array([1, 2, 3, 4, 5, 6])

In [33]:
b

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [36]:
# Subtraction
g = b - a
g

array([[0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3]])

In [37]:
# Additon
h = a+ b
h

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

In [39]:
# another addtion method
h1 = np.add(a,b)
h1

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

In [42]:
# Multiplication
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36],
       [ 4, 10, 18, 28, 40, 54]])

In [41]:
# divison
j = b / a
j

array([[1.  , 1.  , 1.  , 1.  , 1.  , 1.  ],
       [4.  , 2.5 , 2.  , 1.75, 1.6 , 1.5 ]])

In [43]:
# square of each element in a
k = a**2
k

array([ 1,  4,  9, 16, 25, 36])

In [51]:
# empty array
empty = np.empty((2,4))
print(empty)
print('__ ____ ____ ___')
print(empty[0]) # this will show te first index of the array

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
__ ____ ____ ___
[1. 1. 1. 1.]


## Range

In [53]:
x = np.arange(6) # 6 numbers from 0 to 5
x

array([0, 1, 2, 3, 4, 5])

In [54]:
# even number range
even = np.arange(0, 20, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
# Odd number range
odd = np.arange(1, 20, 2)
odd


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [56]:
# specific difference between numbers array
diff = np.arange(1, 27, 4)
diff

array([ 1,  5,  9, 13, 17, 21, 25])

## Create an array of Random Number with same difference in between two numbers

This will create an array of 10 values with same difference inbetween 0 to 10. then are increase or decrease gradually with same distance/differance


In [58]:
# Linear array of 10
linear = np.linspace(0, 10, 10)
linear


array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [61]:
# Linear array of 10
linear = np.linspace(0, -18, num=10)
linear

array([  0.,  -2.,  -4.,  -6.,  -8., -10., -12., -14., -16., -18.])

In [63]:
# array with datatype
linear = np.linspace(0, 18, num=10, dtype=np.int64)
linear

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int64)

## Array with defiend dtype

In [64]:
# define the dthpe of array
x = np.ones(2, dtype=np.float64)
x

array([1., 1.])

In [65]:
# define the dthpe of array
x = np.ones(4, dtype=np.int64)
x

array([1, 1, 1, 1], dtype=int64)

In [67]:
# Range with dtype
x = np.arange(0, 13, 2, dtype=np.int64)
x

array([ 0,  2,  4,  6,  8, 10, 12], dtype=int64)

In [68]:
# Range with dtype
x = np.arange(0, 13, 2, dtype=np.float64)
x

array([ 0.,  2.,  4.,  6.,  8., 10., 12.])

# **Assignment:** What is the difference between int32, int64, float32, and float64

The main difference between `int32`, `int64`, `float32`, and `float64` is the amount of memory they use and the range of values they can represent.

`int32` and `float32` use 32 bits (4 bytes) of memory, while `int64` and `float64` use 64 bits (8 bytes) of memory. This means that `int64` and `float64` can represent larger numbers and more precise decimal values than `int32` and `float32`.

Here's a summary of the range of values that each data type can represent:

- `int32`: signed integers from -2,147,483,648 to 2,147,483,647
- `int64`: signed integers from -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807
- `float32`: single-precision floating-point numbers with 7 decimal digits of precision
- `float64`: double-precision floating-point numbers with 15 decimal digits of precision

In general, you should choose a data type that is appropriate for the range of values and precision that you need for your calculations. If you need to represent large integers or precise decimal values, you should use `int64` or `float64`. If you don't need as much precision, you can use `int32` or `float32` to save memory.

## Sorting an array


In [70]:
# sorting an array
arr = np.array([1,3,2,4,6,5,8,7,10,9])
arr

array([ 1,  3,  2,  4,  6,  5,  8,  7, 10,  9])

In [72]:
arr = np.sort(arr)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Concatination


In [73]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [75]:
# Concatinate a and b
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
# concatinate 2 dimantional array
x = np.array([[1,2,3],[4,5,6]]) # 2  by 3 matrix
y = np.array([[7,8,9]]) # 1 by 3 matrix

In [78]:
#concatinate 2d array (x and y)
z = np.concatenate((x,y))
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Put the arrays on AXIS

In [79]:
# x and y on 0 axis
z = np.concatenate((x,y), axis=0)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:

# Data should have same rows and columns in both arrays if there is a need to put them on axis =1
e = np.array([[7,8,9],[10, 11, 12],[13,14,15]])
x = np.array([[1,2,3],[4,5,6],[1,4,7]]) # 3  by 3 matrix

z1 = np.concatenate((e, z), axis=1)
z1

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6],
       [13, 14, 15,  7,  8,  9]])

## 3D data

In [88]:
t= np.array([[[0, 1, 2, 3],
            [4, 5, 6, 7]],

            [[0, 1, 2, 3],
            [4, 5, 6, 7]],

            [[0 ,1 ,2, 3],
            [4, 5, 6, 7]]])
print(t.shape)
print('- - - - - - ')
print(t)

(3, 2, 4)
- - - - - - 
[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [90]:
# create 3D array of size (3,1,5)
r = np.array([[[0,1,2,3,4]],
              [[5,6,7,8,9]],
              [[10,11,12,13,14]]])
print(r.shape)
print('- - - - - - ')
print(r)

(3, 1, 5)
- - - - - - 
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]


In [91]:
# reshare r array
r1 = r.reshape(5,3)
print(r1.shape)
print('- - - - - - ')
print(r1)


(5, 3)
- - - - - - 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [92]:
# reshape r by 3,5,1
r2 = r.reshape(3,5,1)
print(r2.shape)
print('- - - - - - ')
print(r2)


(3, 5, 1)
- - - - - - 
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]]


In [105]:
# create a 1D array
a = np.arange(12)
print(a)
print('- - - - - - ')
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
- - - - - - 
(12,)


In [106]:
# convert a to 2D array
a2 = a[np.newaxis, :]
print(a2)
print('- - - - - - ')
print(a2.shape)


[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
- - - - - - 
(1, 12)


In [107]:
# change the axis of a2 array
a3 = a[:, np.newaxis]
print(a3)
print("_ _ _ _ _")
print(a3.shape)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
_ _ _ _ _
(12, 1)


In [108]:
# slice the data in a
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [109]:
a[-3: ]

array([ 9, 10, 11])

In [110]:
a[1]


1

In [111]:
# Slice the data with two conditions
a[(a>2) & (a<5)]



array([3, 4])

In [112]:
# use three conditions and filter the arrays
a[(a>2) & (a<5) & (a%2==0)]


array([4])